# Generated by Django 4.2.1 on 2023-06-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['id']},
        ),
    ]
