# Generated by Django 4.2.1 on 2023-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_news_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaming',
            name='video_url',
        ),
        migrations.AddField(
            model_name='streaming',
            name='video',
            field=models.FileField(default=1, upload_to='video'),
            preserve_default=False,
        ),
    ]
