# Generated by Django 4.2.1 on 2023-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_streaming_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streaming',
            name='video',
        ),
        migrations.AddField(
            model_name='streaming',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
