# Generated by Django 4.2.1 on 2023-06-13 14:23

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutimage/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image', models.ImageField(upload_to='blogsimage')),
                ('date', models.DateField(auto_now=True)),
                ('details_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('team_1', models.CharField(max_length=255)),
                ('team_2', models.CharField(max_length=255)),
                ('team1_image', models.ImageField(upload_to='matchimage')),
                ('team2_image', models.ImageField(upload_to='matchimage')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='blogimage')),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('ctg_slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='category_name', unique=True)),
                ('order_number', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='blogimage/')),
                ('description', models.TextField(max_length=10000)),
                ('created_date', models.DateField(auto_now=True)),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title', unique=True)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.sportscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Atheletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='atheletesimage/')),
                ('description', models.TextField(max_length=10000)),
                ('atheletes_slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name', unique=True)),
                ('atheletes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atheletes', to='app.sportscategory')),
            ],
        ),
    ]
