# Generated by Django 4.2.1 on 2023-06-24 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
    ]
