# Generated by Django 4.2.1 on 2023-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_match_options_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
