# Generated by Django 4.2.1 on 2023-06-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='title',
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='app.sportscategory'),
            preserve_default=False,
        ),
    ]
