# Generated by Django 4.2.1 on 2023-06-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_about_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsAndHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.PositiveIntegerField()),
                ('gold', models.CharField(max_length=100)),
                ('silver', models.CharField(max_length=100)),
                ('bronze', models.CharField(max_length=100)),
                ('fourth', models.CharField(max_length=100)),
                ('fifth', models.CharField(max_length=100)),
                ('sixth', models.CharField(max_length=100)),
                ('seventh', models.CharField(max_length=100)),
                ('eighth', models.CharField(max_length=100)),
                ('nineth', models.CharField(max_length=100)),
                ('tenth', models.CharField(max_length=100)),
            ],
        ),
    ]
