# Generated by Django 4.2.1 on 2023-06-29 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_resultsandhighlights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsandhighlights',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='resultsandhighlights',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='app.sportscategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resultsandhighlights',
            name='date',
            field=models.DateField(),
        ),
    ]
